# Generated by Django 6.0 on 2025-12-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_contactinquiry_feedback_slider_delete_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='admin_reply',
            field=models.TextField(blank=True, help_text='The reply from the admin.', null=True),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
